# See https://doc.rust-lang.org/clippy/lint_configuration.html
# for full configuration options.

msrv = "1.89"

doc-valid-idents = [
  "MerkleDB",
  # this list must end with ".." so that it does not truncate the default list
  "..",
]

disallowed-methods = [
  { path = "rand::rng", replacement = "firewood_storage::StdRng::from_env_or_random", reason = "use a prng with a user-defined seed instead", allow-invalid = true },
]

disallowed-types = [
  { path = "rand::SeedableRng", replacement = "firewood_storage::StdRng", reason = "use a prng with a user-defined seed instead", allow-invalid = true },
  { path = "rand::rngs::StdRng", replacement = "firewood_storage::StdRng", reason = "use a prng with a user-defined seed instead", allow-invalid = true },
]
