edition = "2018"
unstable_features = true
max_width = 120
binop_separator = "Back"
inline_attribute_width = 80
fn_args_layout = "Compressed"
hard_tabs = false
tab_spaces = 4
trailing_semicolon = false
