# As mentioned by https://github.com/golang/go/wiki/Ubuntu
- name: Add Go repository
  become: true
  apt_repository:
    repo: ppa:longsleep/golang-backports
  tags:
    - golang_base

- name: Install Go
  become: true
  apt:
    name:
      - golang-go
  tags:
    - golang_base
