avalanche_binary: "{{ repo_folder }}/build/avalanchego"
repo_folder: "~{{ ansible_facts.user_id }}/go/src/github.com/ava-labs/avalanchego"
repo_name: ava-labs/avalanchego-internal
repo_url: git@github.com:{{ repo_name }}
repo_branch: db-upgrade
