avalanche_binary: "{{ repo_folder }}/build/avalanchego"
repo_folder: "~{{ ansible_user }}/go/src/github.com/ava-labs/avalanchego"
repo_name: ava-labs/avalanchego
repo_url: https://github.com/{{ repo_name }}
repo_branch: dev
