[package]
name = "firewood"
version = "0.0.7"
edition = "2024"
authors = [
     "Angel Leon <gubatron@gmail.com>",
     "Austin Larson <78000745+alarso16@users.noreply.github.com>",
     "Cesar <137245636+nytzuga@users.noreply.github.com>",
     "Dan Laine <daniel.laine@avalabs.org>",
     "Dan Sover <dan.sover@avalabs.org>",
     "Hao Hao <hao.hao@avalabs.org>",
     "Patrick O'Grady <prohb125@gmail.com>",
     "Richard Pringle <rpring9@gmail.com>",
     "Ron Kuris <ron.kuris@avalabs.org>",
     "Sam Batschelet <sam.batschelet@avalabs.org>",
     "xinifinity <113067541+xinifinity@users.noreply.github.com>",
]
description = "Firewood is an embedded key-value store, optimized to store blockchain state."
license-file = "../LICENSE.md"
homepage = "https://avalabs.org"
repository = "https://github.com/ava-labs/firewood"
readme = "../README.md"

[dependencies]
aquamarine = "0.6.0"
async-trait = "0.1.88"
futures = "0.3.31"
hex = "0.4.3"
metrics = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
test-case = "3.3.1"
thiserror = { workspace = true }
typed-builder = "0.21.0"
bincode = { workspace = true }
integer-encoding = { workspace = true }
smallvec = { workspace = true }
fastrace = { workspace = true }
coarsetime = { workspace = true }
firewood-macros = { version = "0.0.7", path = "../firewood-macros" }

[features]
default = []
nightly = []
io-uring = ["firewood-storage/io-uring"]
logger = ["firewood-storage/logger"]
branch_factor_256 = [ "firewood-storage/branch_factor_256" ]
ethhash = [ "firewood-storage/ethhash" ]

[dev-dependencies]
firewood-triehash = { version = "0.0.7", path = "../triehash" }
criterion = { workspace = true, features = ["async_tokio"] }
rand = { workspace = true }
rand_distr = "0.5.1"
clap = { version = "4.5.40", features = ['derive'] }
pprof = { workspace = true, features = ["flamegraph"] }
tempfile = { workspace = true }
tokio = { version = "1.46.0", features = ["rt", "sync", "macros", "rt-multi-thread"] }
ethereum-types = { workspace = true }
sha3 = "0.10.8"
plain_hasher = "0.2.3"
hex-literal = { workspace = true }
env_logger = "0.11.8"
hash-db = "0.16.0"

[[bench]]
name = "hashops"
harness = false

[target.'cfg(target_os = "linux")'.dependencies]
firewood-storage = { version = "0.0.7", path = "../storage", features = ["io-uring"] }

[target.'cfg(not(target_os = "linux"))'.dependencies]
firewood-storage = { version = "0.0.7", path = "../storage" }

[lints]
workspace = true
