- name: Install Avalanche dependencies
  become: true
  yum:
    name:
      - git
      # Staking key management
      - openssl
      - python-cryptography  # Python 2.x bindings
    state: present
