- name: Dispatch tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts.distribution | lower }}-{{ ansible_facts.distribution_major_version }}.yml"
    - "{{ ansible_facts.distribution | lower }}.yml"
    - "not_supported.yml"
  tags:
    - avalanche_base
