[package]
name = "avalanche-snow"
description = "Snowball/Snowman consensus implementation for Avalanche"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
avalanche-ids = { workspace = true }
avalanche-db = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
parking_lot = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
tokio-test = { workspace = true }

[lints]
workspace = true
