borealis_bootstrap:
  hosts:
      bootstrap1:
        ansible_host: 3.84.129.247
        staking_tls_key_file: "/home/ubuntu/go/src/github.com/ava-labs/gecko/staking/local/staker1.key"
        staking_tls_cert_file: "/home/ubuntu/go/src/github.com/ava-labs/gecko/staking/local/staker1.crt"
  vars:
    ansible_connection: ssh
    ansible_user: ubuntu

    network_id: "local"
    api_admin_enabled: true
    api_keystore_enabled: true
    api_metrics_enabled: true
    ava_tx_fee: 0
    assertions_enabled: true
    signature_verification_enabled: true
    db_enabled: true
    db_dir: "/home/ubuntu/db"
    http_host: ""
    http_port: 21000
    http_tls_enabled: false
    http_tls_key_file: ""
    http_tls_cert_file: ""
    bootstrap_ips: ""
    bootstrap_ids: ""
    staking_port: 21001
    staking_tls_enabled: true
    staking_tls_key_file: "/home/ubuntu/keys/staker.key"
    staking_tls_cert_file: "/home/ubuntu/keys/staker.crt"
    plugin_dir: "/home/ubuntu/go/src/github.com/ava-labs/gecko/build/plugins"
    log_dir: "/home/ubuntu/.gecko"
    log_level: debug
    snow_sample_size: 3
    snow_quorum_size: 2
    snow_virtuous_commit_threshold: 20
    snow_rogue_commit_threshold: 30
    snow_avalanche_num_parents: 5
    snow_avalanche_batch_size: 30
    api_ipcs_enabled: false
    xput_server_enabled: false
    xput_server_port: 21002

borealis_node:
  hosts:
      node1:
        ansible_host: 35.153.99.244
        staking_tls_key_file: "/home/ubuntu/go/src/github.com/ava-labs/gecko/staking/local/staker2.key"
        staking_tls_cert_file: "/home/ubuntu/go/src/github.com/ava-labs/gecko/staking/local/staker2.crt"
      node2:
        ansible_host: 34.201.137.119
        staking_tls_key_file: "/home/ubuntu/go/src/github.com/ava-labs/gecko/staking/local/staker3.key"
        staking_tls_cert_file: "/home/ubuntu/go/src/github.com/ava-labs/gecko/staking/local/staker3.crt"
      node3:
        ansible_host: 54.146.1.110
        staking_tls_key_file: "/home/ubuntu/go/src/github.com/ava-labs/gecko/staking/local/staker4.key"
        staking_tls_cert_file: "/home/ubuntu/go/src/github.com/ava-labs/gecko/staking/local/staker4.crt"
      node4:
        ansible_host: 54.91.255.231
        staking_tls_key_file: "/home/ubuntu/go/src/github.com/ava-labs/gecko/staking/local/staker5.key"
        staking_tls_cert_file: "/home/ubuntu/go/src/github.com/ava-labs/gecko/staking/local/staker5.crt"
  vars:
    ansible_connection: ssh
    ansible_user: ubuntu

    network_id: "local"
    api_admin_enabled: true
    api_keystore_enabled: true
    api_metrics_enabled: true
    ava_tx_fee: 0
    assertions_enabled: true
    signature_verification_enabled: true
    db_enabled: true
    db_dir: "/home/ubuntu/db"
    http_host: ""
    http_port: 21000
    http_tls_enabled: false
    http_tls_key_file: ""
    http_tls_cert_file: ""
    bootstrap_ips: "3.84.129.247:21001"
    bootstrap_ids: "7Xhw2mDxuDS44j42TCB6U5579esbSt3Lg"
    staking_port: 21001
    staking_tls_enabled: true
    staking_tls_key_file: "/home/ubuntu/keys/staker.key"
    staking_tls_cert_file: "/home/ubuntu/keys/staker.crt"
    plugin_dir: "/home/ubuntu/go/src/github.com/ava-labs/gecko/build/plugins"
    log_dir: "/home/ubuntu/.gecko"
    log_level: debug
    snow_sample_size: 3
    snow_quorum_size: 2
    snow_virtuous_commit_threshold: 20
    snow_rogue_commit_threshold: 30
    snow_avalanche_num_parents: 5
    snow_avalanche_batch_size: 30
    api_ipcs_enabled: false
    xput_server_enabled: false
    xput_server_port: 21002
