# Build a debian package from the avalanchego repo 

name: build-linux-arm64-release

# Controls when the action will run.
on:
  push:
    tags:
      - '*' # Push events to every tag

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-arm64:
    # The type of runner that the job will run on
    runs-on: self-hosted 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Build the avalanchego binaries 
      run: ./scripts/build.sh 

    - name: Install aws cli
      run: sudo apt-get install awscli

    - name: Install rpmbuild
      run: sudo apt-get install rpm 

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      shell: bash

    - name: Create debian package structure
      run: ./.github/workflows/build-deb-pkg.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.UPLOAD_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.UPLOAD_KEY }}
        TAG: ${{ steps.get_version.outputs.VERSION }}
        BUCKET: ${{ secrets.BUCKET }}
        ARCH: "arm64"

    - name: Create tgz package structure
      run: ./.github/workflows/build-tgz-pkg.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.UPLOAD_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.UPLOAD_KEY }}
        TAG: ${{ steps.get_version.outputs.VERSION }}
        BUCKET: ${{ secrets.BUCKET }}
        ARCH: "arm64"
