# Deploy automatically to internal testnet 

name: deploy-internal 

# Controls when the action will run.
on:
  push:
    branch:
      - 'deploy-internal' # Triggers on every push to the `deploy-internal` branch 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Build the avalanchego binaries 
      run: ./scripts/build.sh 

    - name: Install aws cli
      run: sudo apt-get install awscli

    - name: Get the commit id 
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_SHA::8}
      shell: bash

    - name: Create debian package structure
      run: ./.github/workflows/build-deb-pkg.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.INTERNAL_BUILDS_ID}}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.INTERNAL_BUILDS_KEY}}
        TAG: ${{ steps.get_version.outputs.VERSION }}
        BUCKET: ${{ secrets.INTERNAL_BUILDS_BUCKET }}

    - name: Run ansible deployment playbook 
      run:  ansible-playbook --private-key ${{ secrets.DEPLOY_USER }} -l ${{ secrets.INVENTORY }} play-deploy-internal.yml
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.INTERNAL_BUILDS_ID}}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.INTERNAL_BUILDS_KEY}}
        BUCKET: ${{ secrets.INTERNAL_BUILDS_BUCKET }}
        DEB_FILE: avalanchego-linux_${{ steps.get_version.outputs.VERSION }}.deb
