name: Publish Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - master
      - dev

jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install qemu (required for cross-platform builds)
        run: |
          sudo apt update
          sudo apt -y install qemu-system qemu-user-static
          sudo systemctl restart docker
      - name: Create multiplatform docker builder
        run: docker buildx create --use
      - name: Build and publish images to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          DOCKER_IMAGE: ${{ secrets.DOCKER_REPO }}
          BUILD_MULTI_ARCH: 1
        run: scripts/run_task.sh build-image
      - name: Build and publish bootstrap-monitor image to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          DOCKER_IMAGE: avaplatform/bootstrap-monitor
          BUILD_MULTI_ARCH: 1
        run: scripts/run_task.sh build-bootstrap-monitor-image
      - name: Build and publish subnet-evm image to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          DOCKER_IMAGE: avaplatform/subnet-evm
          BUILD_MULTI_ARCH: 1
          AVALANCHEGO_NODE_IMAGE_REPO: ${{ secrets.DOCKER_REPO }}
        run: scripts/run_task.sh build-subnet-evm-image
