name: publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish-firewood-crate:
    name: firewood-lib
    runs-on: ubuntu-latest
    if: "startsWith(github.event.release.tag_name, 'v')"
    steps:
      - uses: actions/checkout@v1
      - uses: dtolnay/rust-toolchain@stable
      - name: publish shale crate
        continue-on-error: true
        run: |
          cargo login ${{ secrets.CARGO_TOKEN }}
          cargo publish -p firewood-shale
      - name: publish libaio crate
        continue-on-error: true
        run: |
          cargo login ${{ secrets.CARGO_TOKEN }}
          cargo publish -p firewood-libaio
      - name: publish growth-ring crate
        continue-on-error: true
        run: |
          cargo login ${{ secrets.CARGO_TOKEN }}
          cargo publish -p firewood-growth-ring
      - name: publish firewood crate
        continue-on-error: false
        run: |
          cargo login ${{ secrets.CARGO_TOKEN }}
          cargo publish -p firewood
