name: e2e Tests + Publish Docker Image

on:
  push:
    tags:
      - "*" # Push events to every tag
    branches:
      - master
      - dev

jobs:
  run_e2e_tests_plus_publish_image:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run Kurtosis Tests
        env:
          KURTOSIS_CLIENT_ID: ${{ secrets.kurtosis_client_id }}
          KURTOSIS_CLIENT_SECRET: ${{ secrets.kurtosis_client_secret }}
          DOCKER_USERNAME: ${{ secrets.docker_username }}
          DOCKER_PASS: ${{ secrets.docker_pass }}
          DOCKER_REPO: ${{ secrets.docker_repo }}
        run: .github/workflows/run_e2e_tests.sh avalanchego --parallelism 2 --client-id $KURTOSIS_CLIENT_ID --client-secret $KURTOSIS_CLIENT_SECRET

      - name: Publish image to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.docker_username }}
          DOCKER_PASS: ${{ secrets.docker_pass }}
          DOCKER_REPO: ${{ secrets.docker_repo }}

        run: .github/workflows/publish_image.sh
